name: yamlfmt
title: yamlfmt
version: "0.15.0"
summary: yamlfmt is an extensible command line tool or library to format yaml files.
description: |
  yamlfmt is an extensible command line tool or library to format yaml files.

  Goals:

  - Create a command line yaml formatting tool that is easy to distribute (single binary)
  - Make it simple to extend with new custom formatters
  - Enable alternative use as a library, providing a foundation for users to create a tool that meets specific needs
base: core24
confinement: strict
apps:
  yamlfmt:
    command: bin/yamlfmt
    plugs:
      - home
parts:
  yamlfmt:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/google/yamlfmt.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - golang
    build-environment:
      - GOBIN: $CRAFT_PART_INSTALL/bin
